"""
Strategy Interface - Base class and types for trading strategies.

Provides the foundation for implementing trading strategies that
consume enriched tick data via Redis pub/sub.
"""

from __future__ import annotations

import logging
from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from datetime import UTC, datetime
from decimal import Decimal
from enum import Enum
from typing import Any
from uuid import UUID

from src.domain.strategies.price_statistics import SymbolPriceStatistics

logger = logging.getLogger(__name__)

_price_stats: SymbolPriceStatistics | None = None


def get_price_statistics() -> SymbolPriceStatistics:
    """Get the shared SymbolPriceStatistics instance.

    Returns:
        Shared statistics tracker for all strategies.
    """
    global _price_stats
    if _price_stats is None:
        _price_stats = SymbolPriceStatistics()
    return _price_stats


def reset_price_statistics() -> None:
    """Reset the shared statistics instance (useful for tests)."""
    global _price_stats
    _price_stats = None


class SignalType(Enum):
    """Type of trading signal."""

    BUY = "BUY"
    SELL = "SELL"
    HOLD = "HOLD"
    CLOSE_LONG = "CLOSE_LONG"
    CLOSE_SHORT = "CLOSE_SHORT"


class TimeFrame(Enum):
    """Strategy time frame."""

    TICK = "TICK"
    SECOND = "1S"
    MINUTE = "1M"
    FIVE_MINUTE = "5M"
    FIFTEEN_MINUTE = "15M"
    HOUR = "1H"
    FOUR_HOUR = "4H"
    DAY = "1D"


class StrategyState(Enum):
    """Strategy running state."""

    STOPPED = "STOPPED"
    RUNNING = "RUNNING"
    PAUSED = "PAUSED"
    ERROR = "ERROR"


@dataclass
class Signal:
    """
    Trading signal generated by strategy.

    Attributes:
        strategy_id: Unique strategy identifier
        symbol: Trading pair (e.g., "BTC/USDT")
        signal_type: BUY, SELL, HOLD, etc.
        price: Current price when signal generated
        timestamp: Signal generation time
        confidence: Signal confidence (0.0-1.0)
        metadata: Additional signal data
    """

    strategy_id: str
    symbol: str
    signal_type: SignalType
    price: Decimal
    timestamp: datetime = field(default_factory=lambda: datetime.now(UTC))
    confidence: float = 0.5
    metadata: dict[str, Any] = field(default_factory=dict)

    def to_dict(self) -> dict[str, Any]:
        """Convert signal to dictionary."""
        return {
            "strategy_id": self.strategy_id,
            "symbol": self.symbol,
            "signal_type": self.signal_type.value,
            "price": float(self.price),
            "timestamp": self.timestamp.isoformat(),
            "confidence": self.confidence,
            "metadata": self.metadata,
        }


@dataclass
class Position:
    """
    Trading position.

    Attributes:
        symbol: Trading pair
        side: LONG or SHORT
        quantity: Position size
        entry_price: Average entry price
        current_price: Current market price
        unrealized_pnl: Unrealized profit/loss
        opened_at: Position open time
    """

    symbol: str
    side: str  # LONG or SHORT
    quantity: Decimal
    entry_price: Decimal
    current_price: Decimal = Decimal("0")
    take_profit_price: Decimal | None = None
    stop_loss_price: Decimal | None = None
    unrealized_pnl: Decimal = Decimal("0")
    opened_at: datetime = field(default_factory=lambda: datetime.now(UTC))

    def update_price(self, price: Decimal) -> None:
        """Update current price and calculate PnL."""
        self.current_price = price
        if self.side == "LONG":
            self.unrealized_pnl = (price - self.entry_price) * self.quantity
        else:  # SHORT
            self.unrealized_pnl = (self.entry_price - price) * self.quantity

    @property
    def pnl_percent(self) -> float:
        """Get PnL as percentage."""
        if self.entry_price == 0:
            return 0.0
        return float(self.unrealized_pnl / self.entry_price * 100)

    def is_take_profit_hit(self, price: Decimal) -> bool:
        """Check if current price hits the take-profit level."""
        if self.take_profit_price is None:
            return False
        if self.side == "LONG":
            return price >= self.take_profit_price
        return price <= self.take_profit_price

    def is_stop_loss_hit(self, price: Decimal) -> bool:
        """Check if current price hits the stop-loss level."""
        if self.stop_loss_price is None:
            return False
        if self.side == "LONG":
            return price <= self.stop_loss_price
        return price >= self.stop_loss_price

    def to_dict(self) -> dict[str, Any]:
        """Convert position to dictionary."""
        return {
            "symbol": self.symbol,
            "side": self.side,
            "quantity": float(self.quantity),
            "entry_price": float(self.entry_price),
            "current_price": float(self.current_price),
            "take_profit_price": float(self.take_profit_price) if self.take_profit_price else None,
            "stop_loss_price": float(self.stop_loss_price) if self.stop_loss_price else None,
            "unrealized_pnl": float(self.unrealized_pnl),
            "pnl_percent": self.pnl_percent,
            "opened_at": self.opened_at.isoformat(),
        }


@dataclass
class EnrichedTick:
    """
    Enriched tick data from enrichment service.

    Attributes:
        symbol: Trading pair
        price: Current price
        volume: Current volume
        time: Tick timestamp
        indicators: Dictionary of indicator values
    """

    symbol: str
    price: Decimal
    volume: Decimal
    time: datetime
    indicators: dict[str, float] = field(default_factory=dict)

    @classmethod
    def from_message(cls, message: dict[str, Any]) -> EnrichedTick:
        """Create EnrichedTick from Redis message."""
        return cls(
            symbol=message.get("symbol", ""),
            price=Decimal(str(message.get("price", 0))),
            volume=Decimal(str(message.get("volume", 0))),
            time=datetime.fromisoformat(message.get("time", datetime.now(UTC).isoformat())),
            indicators=message.get("indicators", {}),
        )

    def get_indicator(self, name: str, default: float = 0.0) -> float:
        """Get indicator value by name."""
        return self.indicators.get(name, default)


class Strategy(ABC):
    """
    Abstract base class for trading strategies.

    Purpose:
        Defines the interface for all trading strategies.
        Strategies consume enriched tick data via Redis pub/sub
        and generate trading signals.

    Lifecycle:
        1. initialize() - Setup (load config, validate)
        2. start() - Begin processing ticks
        3. on_tick() - Called for each tick (implement this)
        4. stop() - Cleanup

    Example:
        >>> class RSIStrategy(Strategy):
        ...     def on_tick(self, tick: EnrichedTick) -> Optional[Signal]:
        ...         rsi = tick.get_indicator('rsiindicator_period14_rsi')
        ...         if rsi < 30:
        ...             return Signal(self.id, tick.symbol, SignalType.BUY, tick.price)
        ...         return None
    """

    def __init__(
        self,
        strategy_id: str,
        symbols: list[str],
        time_frame: TimeFrame = TimeFrame.TICK,
    ) -> None:
        """
        Initialize strategy.

        Args:
            strategy_id: Unique strategy identifier
            symbols: List of symbols to trade (e.g., ['BTC/USDT'])
            time_frame: Strategy time frame

        Raises:
            ValueError: If strategy_id or symbols is empty
        """
        if not strategy_id:
            raise ValueError("strategy_id cannot be empty")
        if not symbols:
            raise ValueError("symbols list cannot be empty")

        self._strategy_id: str = strategy_id
        self._symbols: list[str] = symbols
        self._time_frame: TimeFrame = time_frame

        # State
        self._state: StrategyState = StrategyState.STOPPED
        self._positions: dict[str, Position] = {}
        self._signals: list[Signal] = []
        self._ticks_processed: int = 0
        self._errors: int = 0
        self._open_positions_count: int = 0

        # Configuration
        self._config: dict[str, Any] = {}

        # Common strategy configuration defaults (shared by derived classes)
        self.last_macd: float = 0.0
        self.last_signal: float = 0.0
        self.last_histogram: float = 0.0
        self.prev_macd: float = 0.0
        self.signal_count: int = 0
        self.macd_indicator_name: str = "macdsmaindicator"
        self.fast_period: int = 12
        self.slow_period: int = 26
        self.signal_period: int = 9
        self.min_relative_threshold: float = 0.001
        self.bottom_border_macd_to_buy: float = 0.0
        self.grid_quantity_absolute: float = 100.0
        self.grid_profit_pct: float = 0.85
        self.sma_fast: str | None = None
        self.sma_slow: str | None = None
        self.sma_multiplicator: float = 0.997
        self.avg_multiplicator_day: float = 0.991
        self.avg_multiplicator_week: float = 0.991
        self.rsi_99_threshold: float = 32.0
        self.trend_lookback: int = 3
        self.max_open_positions: int = 5
        self.macd_slow_indicator_name: str = "macd_8590_13800_195"

        # Dynamic threshold state (used by _is_macd_change_noise)
        self._macd_change_history: list[float] = []
        self._last_macd_value: float | None = None

        logger.info(f"Strategy {strategy_id} initialized for {len(symbols)} symbols")

    @property
    def id(self) -> str:
        """Get strategy ID."""
        return self._strategy_id

    @property
    def symbols(self) -> list[str]:
        """Get symbols list."""
        return self._symbols.copy()

    @property
    def state(self) -> StrategyState:
        """Get strategy state."""
        return self._state

    @property
    def positions(self) -> dict[str, Position]:
        """Get current positions."""
        return self._positions.copy()

    @property
    def ticks_processed(self) -> int:
        """Get number of ticks processed."""
        return self._ticks_processed

    @abstractmethod
    def on_tick(self, tick: EnrichedTick) -> Signal | None:
        """
        Process enriched tick and generate signal.

        This is the main strategy logic method.
        Called for each incoming tick from Redis pub/sub.

        Args:
            tick: Enriched tick data with indicators

        Returns:
            Signal if generated, None otherwise

        Example:
            >>> def on_tick(self, tick: EnrichedTick) -> Optional[Signal]:
            ...     rsi = tick.get_indicator('rsiindicator_period14_rsi')
            ...     if rsi < 30:
            ...         return Signal(self.id, tick.symbol, SignalType.BUY, tick.price)
            ...     return None
        """
        pass

    async def initialize(self) -> bool:
        """
        Initialize strategy.

        Called before start(). Load configuration,
        validate parameters, setup resources.

        Returns:
            True if initialization successful

        Example:
            >>> await strategy.initialize()
            True
        """
        logger.info(f"Initializing strategy {self._strategy_id}")
        return True

    async def start(self) -> None:
        """
        Start strategy.

        Begins processing ticks. Called after initialize().
        """
        logger.info(f"Starting strategy {self._strategy_id}")
        self._state = StrategyState.RUNNING

    async def stop(self) -> None:
        """
        Stop strategy.

        Stops processing ticks. Cleanup resources.
        """
        logger.info(f"Stopping strategy {self._strategy_id}")
        self._state = StrategyState.STOPPED

    async def pause(self) -> None:
        """Pause strategy."""
        logger.info(f"Pausing strategy {self._strategy_id}")
        self._state = StrategyState.PAUSED

    async def resume(self) -> None:
        """Resume paused strategy."""
        logger.info(f"Resuming strategy {self._strategy_id}")
        self._state = StrategyState.RUNNING

    def process_tick(self, tick: EnrichedTick) -> Signal | None:
        """
        Process tick with state management.

        Wrapper around on_tick() that handles TP/SL checks,
        state validation and error tracking.

        Args:
            tick: Enriched tick data

        Returns:
            Signal if generated, None otherwise
        """
        if self._state != StrategyState.RUNNING:
            logger.debug(
                f"[{self._strategy_id}] Skip tick: strategy not running "
                f"(state={self._state.value})"
            )
            return None

        if tick.symbol not in self._symbols:
            logger.debug(f"[{self._strategy_id}] Skip tick: symbol {tick.symbol} not in strategy")
            return None

        self._ticks_processed += 1

        # Check TP/SL for positions on this symbol first
        close_signal = self._check_positions(tick)
        if close_signal:
            self._signals.append(close_signal)
            logger.info(
                f"Position auto-closed: {close_signal.signal_type.value} "
                f"{close_signal.symbol} @ {close_signal.price}"
            )
            return close_signal

        # Enforce max open positions — skip strategy logic when limit reached
        if self._open_positions_count >= self.max_open_positions:
            logger.debug(
                f"[{self._strategy_id}] Skip logic: "
                f"{self._open_positions_count} >= {self.max_open_positions} max open positions"
            )
            return None

        signal = self.on_tick(tick)

        if signal:
            self._signals.append(signal)
            qty_usdc = signal.metadata.get("quantity_usdc")
            if qty_usdc is not None:
                qty = Decimal(str(qty_usdc)) / signal.price
                logger.info(
                    f"Signal generated: {signal.signal_type.value} {signal.symbol} @ {signal.price}, "
                    f"qty={qty:.8f}, sum={float(qty_usdc):.2f} USDC"
                )
            else:
                logger.info(
                    f"Signal generated: {signal.signal_type.value} {signal.symbol} @ {signal.price}"
                )
        else:
            logger.debug(
                f"[{self._strategy_id}] No signal from on_tick for {tick.symbol} @ {tick.price}"
            )

        return signal

    def _check_positions(self, tick: EnrichedTick) -> Signal | None:
        """Check open positions for take-profit and stop-loss hits.

        Updates the position's current price, then checks whether the
        configured take-profit or stop-loss level has been triggered.
        If so, the position is closed and a corresponding close signal
        is returned.

        Args:
            tick: Enriched tick data

        Returns:
            A close signal if a TP/SL was triggered, ``None`` otherwise.
        """
        symbol = tick.symbol
        if symbol not in self._positions:
            return None

        position = self._positions[symbol]
        price = tick.price
        position.update_price(price)

        exit_reason: str | None = None
        if position.is_take_profit_hit(price):
            exit_reason = "take_profit"
        elif position.is_stop_loss_hit(price):
            exit_reason = "stop_loss"

        if exit_reason is None:
            return None

        closed = self.close_position(symbol, price)
        if closed is None:
            return None

        signal_type = SignalType.SELL if closed.side == "LONG" else SignalType.CLOSE_SHORT
        logger.info(
            f"[{self._strategy_id}] TP/SL triggered for {symbol}: "
            f"{exit_reason}, PnL={closed.unrealized_pnl} ({closed.pnl_percent:.2f}%)"
        )

        self.on_position_closed(symbol, price, exit_reason, grid_index=None)

        return Signal(
            strategy_id=self._strategy_id,
            symbol=symbol,
            signal_type=signal_type,
            price=price,
            confidence=1.0,
            metadata={
                "reason": exit_reason,
                "quantity": closed.quantity,
                "entry_price": float(closed.entry_price),
                "pnl": float(closed.unrealized_pnl),
                "pnl_percent": closed.pnl_percent,
            },
        )

    def update_position(self, symbol: str, price: Decimal) -> None:
        """
        Update position with current price.

        Args:
            symbol: Trading pair symbol
            price: Current price
        """
        if symbol in self._positions:
            self._positions[symbol].update_price(price)

    def open_position(
        self,
        symbol: str,
        side: str,
        quantity: Decimal,
        price: Decimal,
        take_profit_price: Decimal | None = None,
        stop_loss_price: Decimal | None = None,
    ) -> Position | None:
        """
        Open new position.

        Args:
            symbol: Trading pair
            side: LONG or SHORT
            quantity: Position size
            price: Entry price
            take_profit_price: Price at which to auto-close for profit
            stop_loss_price: Price at which to auto-close to limit loss

        Returns:
            New position, or None if ``max_open_positions`` limit is reached
        """
        if len(self._positions) >= self.max_open_positions:
            logger.warning(
                f"[{self._strategy_id}] Cannot open {side} {symbol}: "
                f"max_open_positions ({self.max_open_positions}) reached"
            )
            return None

        position = Position(
            symbol=symbol,
            side=side,
            quantity=quantity,
            entry_price=price,
            current_price=price,
            take_profit_price=take_profit_price,
            stop_loss_price=stop_loss_price,
        )
        self._positions[symbol] = position
        logger.info(
            f"Opened {side} position: {quantity} {symbol} @ {price} "
            f"(TP={take_profit_price}, SL={stop_loss_price})"
        )
        return position

    def get_position(self, symbol: str) -> Position | None:
        """Get open position for a symbol, or None.

        Args:
            symbol: Trading pair

        Returns:
            Position if open, None otherwise
        """
        return self._positions.get(symbol)

    def close_position(self, symbol: str, price: Decimal) -> Position | None:
        """
        Close existing position.

        Args:
            symbol: Trading pair symbol
            price: Close price

        Returns:
            Closed position if existed, None otherwise
        """
        if symbol not in self._positions:
            return None

        position = self._positions.pop(symbol)
        position.update_price(price)

        logger.info(
            f"Closed position: {position.side} {symbol} "
            f"PnL: {position.unrealized_pnl} ({position.pnl_percent:.2f}%)"
        )

        return position

    def register_open_position(self) -> None:
        """Increment the open-position counter (called by the backtest engine)."""
        self._open_positions_count += 1

    def register_close_position(self) -> None:
        """Decrement the open-position counter (called by the backtest engine)."""
        if self._open_positions_count > 0:
            self._open_positions_count -= 1

    @abstractmethod
    def on_position_closed(
        self,
        symbol: str,
        price: Decimal,
        exit_reason: str,
        grid_index: int | None = None,
    ) -> None:
        """
        Called when the backtest engine closes a position externally
        (stop loss, take profit, or end of test).

        Strategies can override this to clean up internal state.

        Args:
            symbol: Trading pair symbol
            price: Price at which position was closed
            exit_reason: Reason for closure (stop_loss, take_profit, end_of_test, etc.)
            grid_index: Grid level index if applicable (for grid strategies)
        """
        pass

    def get_config(self, key: str, default: Any = None) -> Any:
        """Get configuration value."""
        return self._config.get(key, default)

    def set_config(self, key: str, value: Any) -> None:
        """Set configuration value."""
        self._config[key] = value

    def load_common_config(self) -> None:
        """Load common strategy configuration from self._config.

        Reads all shared config parameters via ``get_config()`` so derived
        classes can call this once at initialisation instead of repeating the
        same ``self.xxx = self.get_config("xxx", default)`` lines.
        """
        self.macd_indicator_name = self.get_config("macd_indicator_name", "macdsmaindicator")
        self.fast_period = self.get_config("fast_period", 12)
        self.slow_period = self.get_config("slow_period", 26)
        self.signal_period = self.get_config("signal_period", 9)
        self.min_relative_threshold = self.get_config("min_relative_threshold", 0.001)
        self.bottom_border_macd_to_buy = self.get_config("bottom_border_macd_to_buy", 0.0)
        execution_config = self._config.get("execution", {})
        self.grid_quantity_absolute = execution_config.get(
            "grid_quantity_absolute",
            self.get_config("grid_quantity_absolute", 100.0),
        )
        self.grid_profit_pct = execution_config.get(
            "grid_profit_pct",
            self.get_config("grid_profit_pct", 0.85),
        )
        self.sma_fast = self.get_config("sma_fast")
        self.sma_slow = self.get_config("sma_slow")
        self.sma_multiplicator = self.get_config("sma_multiplicator", 0.997)
        self.avg_multiplicator_day = self.get_config("avg_multiplicator_day", 0.991)
        self.avg_multiplicator_week = self.get_config("avg_multiplicator_week", 0.991)
        self.rsi_99_threshold = self.get_config("rsi_99_threshold", 32.0)
        self.trend_lookback = self.get_config("trend_lookback", 3)
        self.max_open_positions = self.get_config("max_open_positions", 5)
        self.macd_slow_indicator_name = self.get_config(
            "macd_slow_indicator_name", "macd_8590_13800_195"
        )

    def _check_sma_filter(self, tick: EnrichedTick) -> bool:
        """Check if current price is below configured SMA indicators.

        Auto-detects SMA indicators from ``tick.indicators`` when
        ``sma_fast`` / ``sma_slow`` are not explicitly configured.

        Args:
            tick: Enriched tick data with indicators

        Returns:
            True if price is below all configured SMAs, or if no SMA filter is configured
        """
        if not self.sma_fast and not self.sma_slow:
            sma_keys = sorted(
                [k for k in tick.indicators if k.startswith("sma_")],
                key=lambda k: int(k.split("_")[1]),
            )
            if len(sma_keys) >= 2:
                self.sma_fast = sma_keys[0]
                self.sma_slow = sma_keys[-1]
                logger.info(
                    f"[{self._strategy_id}] Auto-detected SMA filter: "
                    f"fast={self.sma_fast}, slow={self.sma_slow}"
                )
            elif len(sma_keys) == 1:
                self.sma_fast = sma_keys[0]
                logger.info(f"[{self._strategy_id}] Auto-detected SMA filter: fast={self.sma_fast}")

        if not self.sma_fast and not self.sma_slow:
            return True

        price = float(tick.price)

        if self.sma_fast:
            if self.sma_fast in tick.indicators:
                sma_fast_value = tick.indicators[self.sma_fast] * self.sma_multiplicator
                if price >= sma_fast_value:
                    return False

        if self.sma_slow:
            if self.sma_slow in tick.indicators:
                sma_slow_value = tick.indicators[self.sma_slow] * self.sma_multiplicator
                if price >= sma_slow_value:
                    return False

        return True

    def _is_macd_change_noise(self, macd_value: float) -> bool:
        """Check if MACD tick-to-tick change is noise using a dynamic threshold.

        Tracks the last 200 absolute MACD changes and computes a rolling
        median. Changes below ``median × 0.3`` are considered noise. During
        warmup (< 50 ticks), no filtering is applied.

        Args:
            macd_value: Current MACD value

        Returns:
            True if the change is noise (should be rejected), False otherwise
        """
        if self._last_macd_value is None:
            self._last_macd_value = macd_value
            return False

        macd_change = abs(macd_value - self._last_macd_value)
        self._last_macd_value = macd_value

        self._macd_change_history.append(macd_change)
        if len(self._macd_change_history) > 200:
            self._macd_change_history.pop(0)

        if len(self._macd_change_history) >= 50:
            sorted_changes = sorted(self._macd_change_history)
            median_change = sorted_changes[len(sorted_changes) // 2]
            dynamic_threshold = median_change * 0.3
            return macd_change < dynamic_threshold

        return False

    def get_indicator(self, tick: EnrichedTick, name: str, default: float = 0.0) -> float:
        """Convenience method to get indicator value from tick.

        Args:
            tick: Enriched tick data
            name: Indicator name
            default: Default value if indicator not found

        Returns:
            Indicator value or default
        """
        return tick.get_indicator(name, default)

    def get_avg_price(self, symbol: str, window: str) -> Decimal:
        """Get cached average price for a symbol and time window.

        Averages are updated at most once per hour by the pipeline.

        Args:
            symbol: Trading pair (e.g. "BTC/USDC")
            window: One of ``"day"`` or ``"week"``

        Returns:
            Average price as ``Decimal``. Returns ``Decimal('0')`` if no data is available.
        """
        return get_price_statistics().get_avg_price(symbol, window)

    def get_stats(self) -> dict[str, Any]:
        """
        Get strategy statistics.

        Returns:
            Dictionary with strategy statistics
        """
        active_positions = len([p for p in self._positions.values() if p.unrealized_pnl != 0])
        total_pnl = sum(p.unrealized_pnl for p in self._positions.values())

        return {
            "strategy_id": self._strategy_id,
            "state": self._state.value,
            "symbols": self._symbols,
            "ticks_processed": self._ticks_processed,
            "signals_generated": len(self._signals),
            "active_positions": active_positions,
            "total_unrealized_pnl": float(total_pnl),
            "errors": self._errors,
        }


class StrategyManager:
    """
    Manages multiple strategies.

    Purpose:
        - Start/stop multiple strategies
        - Route enriched ticks to strategies
        - Aggregate signals
        - Monitor strategy health

    Example:
        >>> manager = StrategyManager()
        >>> manager.add_strategy(rsi_strategy)
        >>> manager.add_strategy(macd_strategy)
        >>> await manager.start_all()
        >>> # Process ticks
        >>> for tick in ticks:
        ...     signals = manager.process_tick(tick)
    """

    def __init__(self) -> None:
        """Initialize strategy manager."""
        self._strategies: dict[str, Strategy] = {}
        self._running: bool = False
        logger.info("StrategyManager initialized")

    def add_strategy(self, strategy: Strategy) -> None:
        """
        Add strategy to manager.

        Args:
            strategy: Strategy instance to add

        Raises:
            ValueError: If strategy ID already exists
        """
        if strategy.id in self._strategies:
            raise ValueError(f"Strategy {strategy.id} already exists")

        self._strategies[strategy.id] = strategy
        logger.info(f"Added strategy: {strategy.id}")

    def remove_strategy(self, strategy_id: UUID) -> Strategy | None:
        """
        Remove strategy from manager.

        Args:
            strategy_id: Strategy ID to remove

        Returns:
            Removed strategy if existed, None otherwise
        """
        strategy = self._strategies.pop(strategy_id, None)
        if strategy:
            logger.info(f"Removed strategy: {strategy_id}")
        return strategy

    def get_strategy(self, strategy_id: UUID) -> Strategy | None:
        """Get strategy by ID."""
        return self._strategies.get(strategy_id)

    def list_strategies(self) -> list[UUID]:
        """Get list of strategy IDs."""
        return list(self._strategies.keys())

    async def start_all(self) -> None:
        """Start all strategies."""
        logger.info(f"Starting {len(self._strategies)} strategies")
        self._running = True

        for strategy in self._strategies.values():
            try:
                await strategy.initialize()
                await strategy.start()
            except Exception as e:
                logger.error(f"Failed to start strategy {strategy.id}: {e}")

    async def stop_all(self) -> None:
        """Stop all strategies."""
        logger.info("Stopping all strategies")
        self._running = False

        for strategy in self._strategies.values():
            try:
                await strategy.stop()
            except Exception as e:
                logger.error(f"Error stopping strategy {strategy.id}: {e}")

    def process_tick(self, tick: EnrichedTick) -> list[Signal]:
        """
        Process tick through all strategies.

        Args:
            tick: Enriched tick data

        Returns:
            List of signals generated by all strategies
        """
        if not self._running:
            return []

        signals = []

        for strategy in self._strategies.values():
            try:
                signal = strategy.process_tick(tick)
                if signal:
                    signals.append(signal)
            except Exception as e:
                logger.error(f"Error in strategy {strategy.id}: {e}")

        return signals

    def get_all_signals(self) -> list[Signal]:
        """Get all signals from all strategies."""
        signals = []
        for strategy in self._strategies.values():
            signals.extend(strategy._signals)
        return signals

    def get_stats(self) -> dict[str, Any]:
        """Get statistics for all strategies."""
        return {
            "running": self._running,
            "strategy_count": len(self._strategies),
            "strategies": {sid: strat.get_stats() for sid, strat in self._strategies.items()},
        }
