"""
Strategy Interface - Base class and types for trading strategies.

Provides the foundation for implementing trading strategies that
consume enriched tick data via Redis pub/sub.
"""

import logging
from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from datetime import UTC, datetime
from decimal import Decimal
from enum import Enum
from typing import Any, Optional
from uuid import UUID

from src.domain.strategies.strategy_instance import StrategyInstance

logger = logging.getLogger(__name__)


class SignalType(Enum):
    """Type of trading signal."""

    BUY = "BUY"
    SELL = "SELL"
    HOLD = "HOLD"
    CLOSE_LONG = "CLOSE_LONG"
    CLOSE_SHORT = "CLOSE_SHORT"


class TimeFrame(Enum):
    """Strategy time frame."""

    TICK = "TICK"
    SECOND = "1S"
    MINUTE = "1M"
    FIVE_MINUTE = "5M"
    FIFTEEN_MINUTE = "15M"
    HOUR = "1H"
    FOUR_HOUR = "4H"
    DAY = "1D"


@dataclass
class Signal:
    """
    Trading signal generated by strategy.

    Attributes:
        strategy_id: Unique strategy identifier
        symbol: Trading pair (e.g., "BTC/USDT")
        signal_type: BUY, SELL, HOLD, etc.
        price: Current price when signal generated
        timestamp: Signal generation time
        confidence: Signal confidence (0.0-1.0)
        metadata: Additional signal data
    """

    strategy_id: str
    symbol: str
    signal_type: SignalType
    price: Decimal
    timestamp: datetime = field(default_factory=lambda: datetime.now(UTC))
    confidence: float = 0.5
    metadata: dict[str, Any] = field(default_factory=dict)

    def to_dict(self) -> dict[str, Any]:
        """Convert signal to dictionary."""
        return {
            "strategy_id": self.strategy_id,
            "symbol": self.symbol,
            "signal_type": self.signal_type.value,
            "price": float(self.price),
            "timestamp": self.timestamp.isoformat(),
            "confidence": self.confidence,
            "metadata": self.metadata,
        }


@dataclass
class Position:
    """
    Trading position.

    Attributes:
        symbol: Trading pair
        side: LONG or SHORT
        quantity: Position size
        entry_price: Average entry price
        current_price: Current market price
        unrealized_pnl: Unrealized profit/loss
        opened_at: Position open time
    """

    symbol: str
    side: str  # LONG or SHORT
    quantity: Decimal
    entry_price: Decimal
    current_price: Decimal = Decimal("0")
    unrealized_pnl: Decimal = Decimal("0")
    opened_at: datetime = field(default_factory=lambda: datetime.now(UTC))

    def update_price(self, price: Decimal) -> None:
        """Update current price and calculate PnL."""
        self.current_price = price
        if self.side == "LONG":
            self.unrealized_pnl = (price - self.entry_price) * self.quantity
        else:  # SHORT
            self.unrealized_pnl = (self.entry_price - price) * self.quantity

    @property
    def pnl_percent(self) -> float:
        """Get PnL as percentage."""
        if self.entry_price == 0:
            return 0.0
        return float(self.unrealized_pnl / self.entry_price * 100)

    def to_dict(self) -> dict[str, Any]:
        """Convert position to dictionary."""
        return {
            "symbol": self.symbol,
            "side": self.side,
            "quantity": float(self.quantity),
            "entry_price": float(self.entry_price),
            "current_price": float(self.current_price),
            "unrealized_pnl": float(self.unrealized_pnl),
            "pnl_percent": self.pnl_percent,
            "opened_at": self.opened_at.isoformat(),
        }


@dataclass
class EnrichedTick:
    """
    Enriched tick data from enrichment service.

    Attributes:
        symbol: Trading pair
        price: Current price
        volume: Current volume
        time: Tick timestamp
        indicators: Dictionary of indicator values
    """

    symbol: str
    price: Decimal
    volume: Decimal
    time: datetime
    indicators: dict[str, float] = field(default_factory=dict)

    @classmethod
    def from_message(cls, message: dict[str, Any]) -> "EnrichedTick":
        """Create EnrichedTick from Redis message."""
        return cls(
            symbol=message.get("symbol", ""),
            price=Decimal(str(message.get("price", 0))),
            volume=Decimal(str(message.get("volume", 0))),
            time=datetime.fromisoformat(
                message.get("time", datetime.now(UTC).isoformat())
            ),
            indicators=message.get("indicators", {}),
        )

    def get_indicator(self, name: str, default: float = 0.0) -> float:
        """Get indicator value by name."""
        return self.indicators.get(name, default)


class Strategy(ABC):
    """
    Abstract base class for trading strategies.

    Purpose:
        Defines the interface for all trading strategies.
        Strategies consume enriched tick data via Redis pub/sub
        and generate trading signals.

    Lifecycle:
        1. initialize() - Setup (load config, validate)
        2. start() - Begin processing ticks
        3. on_tick() - Called for each tick (implement this)
        4. stop() - Cleanup

    Example:
        >>> class RSIStrategy(Strategy):
        ...     def on_tick(self, tick: EnrichedTick) -> Optional[Signal]:
        ...         rsi = tick.get_indicator('rsiindicator_period14_rsi')
        ...         if rsi < 30:
        ...             return Signal(self.id, tick.symbol, SignalType.BUY, tick.price)
        ...         return None
    """

    def __init__(
        self,
        strategy_id: UUID,
        symbols: list[str],
        time_frame: TimeFrame = TimeFrame.TICK,
    ) -> None:
        """
        Initialize strategy.

        Args:
            strategy_id: Unique strategy UUID
            symbols: List of symbols to trade (e.g., ['BTC/USDT'])
            time_frame: Strategy time frame

        Raises:
            ValueError: If strategy_id or symbols is empty
        """
        if not strategy_id:
            raise ValueError("strategy_id cannot be None")
        if not symbols:
            raise ValueError("symbols list cannot be empty")

        self._strategy_id: UUID = strategy_id
        self._symbols: list[str] = symbols
        self._time_frame: TimeFrame = time_frame

        logger.info(f"Strategy {strategy_id} initialized for {len(symbols)} symbols")

    @property
    def id(self) -> UUID:
        """Get strategy ID."""
        return self._strategy_id

    @property
    def symbols(self) -> list[str]:
        """Get symbols list."""
        return self._symbols.copy()

    @property
    def time_frame(self) -> TimeFrame:
        """Get time frame."""
        return self._time_frame

    @abstractmethod
    def on_tick(self, tick: EnrichedTick) -> Optional[Signal]:
        """
        Process enriched tick and generate signal.

        This is the main strategy logic method.
        Called for each incoming tick from Redis pub/sub.

        Args:
            tick: Enriched tick data with indicators

        Returns:
            Signal if generated, None otherwise

        Example:
            >>> def on_tick(self, tick: EnrichedTick) -> Optional[Signal]:
            ...     rsi = tick.get_indicator('rsiindicator_period14_rsi')
            ...     if rsi < 30:
            ...         return Signal(self.id, tick.symbol, SignalType.BUY, tick.price)
            ...     return None
        """
        pass


class StrategyManager:
    """
    Manages multiple strategy instances.

    Purpose:
        - Start/stop multiple instances
        - Route enriched ticks to instances
        - Aggregate signals
        - Monitor instance health
    """

    def __init__(self) -> None:
        """Initialize strategy manager."""
        self._instances: dict[UUID, StrategyInstance] = {}
        self._running: bool = False
        logger.info("StrategyManager initialized")

    def add_instance(self, instance: StrategyInstance) -> None:
        """
        Add strategy instance to manager.

        Args:
            instance: StrategyInstance to add

        Raises:
            ValueError: If instance ID already exists
        """
        if instance.id in self._instances:
            raise ValueError(f"StrategyInstance {instance.id} already exists")

        self._instances[instance.id] = instance
        logger.info(f"Added strategy instance: {instance.id}")

    def remove_instance(self, instance_id: UUID) -> Optional[StrategyInstance]:
        """
        Remove strategy instance from manager.

        Args:
            instance_id: StrategyInstance ID to remove

        Returns:
            Removed instance if existed, None otherwise
        """
        instance = self._instances.pop(instance_id, None)
        if instance:
            logger.info(f"Removed strategy instance: {instance_id}")
        return instance

    def get_instance(self, instance_id: UUID) -> Optional[StrategyInstance]:
        """Get strategy instance by ID."""
        return self._instances.get(instance_id)

    def list_instances(self) -> list[UUID]:
        """Get list of strategy instance IDs."""
        return list(self._instances.keys())

    async def start_all(self) -> None:
        """Start all strategy instances."""
        logger.info(f"Starting {len(self._instances)} strategy instances")
        self._running = True

        for instance in self._instances.values():
            try:
                instance.start()
            except Exception as e:
                logger.error(f"Failed to start instance {instance.id}: {e}")

    async def stop_all(self) -> None:
        """Stop all strategy instances."""
        logger.info("Stopping all strategy instances")
        self._running = False

        for instance in self._instances.values():
            try:
                instance.stop()
            except Exception as e:
                logger.error(f"Error stopping instance {instance.id}: {e}")

    def process_tick(self, tick: EnrichedTick) -> list[Signal]:
        """
        Process tick through all strategy instances.

        Args:
            tick: Enriched tick data

        Returns:
            List of signals generated by all instances
        """
        if not self._running:
            return []

        signals = []

        for instance in self._instances.values():
            try:
                signal = instance.process_tick(tick)
                if signal:
                    signals.append(signal)
            except Exception as e:
                logger.error(f"Error in instance {instance.id}: {e}")

        return signals

    def get_all_signals(self) -> list[Signal]:
        """Get all signals from all strategy instances."""
        signals = []
        for instance in self._instances.values():
            signals.extend(instance._signals)
        return signals

    def get_stats(self) -> dict[str, Any]:
        """Get statistics for all strategy instances."""
        return {
            "running": self._running,
            "instance_count": len(self._instances),
            "instances": {sid: inst.get_stats() for sid, inst in self._instances.items()},
        }
