"""
Strategy Interface - Base class and types for trading strategies.

Provides the foundation for implementing trading strategies that
consume enriched tick data via Redis pub/sub.
"""

from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from datetime import datetime, timezone
from decimal import Decimal
from enum import Enum
from typing import Dict, List, Optional, Any
import logging

logger = logging.getLogger(__name__)


class SignalType(Enum):
    """Type of trading signal."""
    BUY = "BUY"
    SELL = "SELL"
    HOLD = "HOLD"
    CLOSE_LONG = "CLOSE_LONG"
    CLOSE_SHORT = "CLOSE_SHORT"


class TimeFrame(Enum):
    """Strategy time frame."""
    TICK = "TICK"
    SECOND = "1S"
    MINUTE = "1M"
    FIVE_MINUTE = "5M"
    FIFTEEN_MINUTE = "15M"
    HOUR = "1H"
    FOUR_HOUR = "4H"
    DAY = "1D"


class StrategyState(Enum):
    """Strategy running state."""
    STOPPED = "STOPPED"
    RUNNING = "RUNNING"
    PAUSED = "PAUSED"
    ERROR = "ERROR"


@dataclass
class Signal:
    """
    Trading signal generated by strategy.

    Attributes:
        strategy_id: Unique strategy identifier
        symbol: Trading pair (e.g., "BTC/USDT")
        signal_type: BUY, SELL, HOLD, etc.
        price: Current price when signal generated
        timestamp: Signal generation time
        confidence: Signal confidence (0.0-1.0)
        metadata: Additional signal data
    """
    strategy_id: str
    symbol: str
    signal_type: SignalType
    price: Decimal
    timestamp: datetime = field(default_factory=lambda: datetime.now(timezone.utc))
    confidence: float = 0.5
    metadata: Dict[str, Any] = field(default_factory=dict)

    def to_dict(self) -> Dict[str, Any]:
        """Convert signal to dictionary."""
        return {
            'strategy_id': self.strategy_id,
            'symbol': self.symbol,
            'signal_type': self.signal_type.value,
            'price': float(self.price),
            'timestamp': self.timestamp.isoformat(),
            'confidence': self.confidence,
            'metadata': self.metadata,
        }


@dataclass
class Position:
    """
    Trading position.

    Attributes:
        symbol: Trading pair
        side: LONG or SHORT
        quantity: Position size
        entry_price: Average entry price
        current_price: Current market price
        unrealized_pnl: Unrealized profit/loss
        opened_at: Position open time
    """
    symbol: str
    side: str  # LONG or SHORT
    quantity: Decimal
    entry_price: Decimal
    current_price: Decimal = Decimal('0')
    unrealized_pnl: Decimal = Decimal('0')
    opened_at: datetime = field(default_factory=lambda: datetime.now(timezone.utc))

    def update_price(self, price: Decimal) -> None:
        """Update current price and calculate PnL."""
        self.current_price = price
        if self.side == 'LONG':
            self.unrealized_pnl = (price - self.entry_price) * self.quantity
        else:  # SHORT
            self.unrealized_pnl = (self.entry_price - price) * self.quantity

    @property
    def pnl_percent(self) -> float:
        """Get PnL as percentage."""
        if self.entry_price == 0:
            return 0.0
        return float(self.unrealized_pnl / self.entry_price * 100)

    def to_dict(self) -> Dict[str, Any]:
        """Convert position to dictionary."""
        return {
            'symbol': self.symbol,
            'side': self.side,
            'quantity': float(self.quantity),
            'entry_price': float(self.entry_price),
            'current_price': float(self.current_price),
            'unrealized_pnl': float(self.unrealized_pnl),
            'pnl_percent': self.pnl_percent,
            'opened_at': self.opened_at.isoformat(),
        }


@dataclass
class EnrichedTick:
    """
    Enriched tick data from enrichment service.

    Attributes:
        symbol: Trading pair
        price: Current price
        volume: Current volume
        time: Tick timestamp
        indicators: Dictionary of indicator values
    """
    symbol: str
    price: Decimal
    volume: Decimal
    time: datetime
    indicators: Dict[str, float] = field(default_factory=dict)

    @classmethod
    def from_message(cls, message: Dict[str, Any]) -> 'EnrichedTick':
        """Create EnrichedTick from Redis message."""
        return cls(
            symbol=message.get('symbol', ''),
            price=Decimal(str(message.get('price', 0))),
            volume=Decimal(str(message.get('volume', 0))),
            time=datetime.fromisoformat(message.get('time', datetime.now(timezone.utc).isoformat())),
            indicators=message.get('indicators', {}),
        )

    def get_indicator(self, name: str, default: float = 0.0) -> float:
        """Get indicator value by name."""
        return self.indicators.get(name, default)


class Strategy(ABC):
    """
    Abstract base class for trading strategies.

    Purpose:
        Defines the interface for all trading strategies.
        Strategies consume enriched tick data via Redis pub/sub
        and generate trading signals.

    Lifecycle:
        1. initialize() - Setup (load config, validate)
        2. start() - Begin processing ticks
        3. on_tick() - Called for each tick (implement this)
        4. stop() - Cleanup

    Example:
        >>> class RSIStrategy(Strategy):
        ...     def on_tick(self, tick: EnrichedTick) -> Optional[Signal]:
        ...         rsi = tick.get_indicator('rsiindicator_period14_rsi')
        ...         if rsi < 30:
        ...             return Signal(self.id, tick.symbol, SignalType.BUY, tick.price)
        ...         return None
    """

    def __init__(
        self,
        strategy_id: str,
        symbols: List[str],
        time_frame: TimeFrame = TimeFrame.TICK,
    ) -> None:
        """
        Initialize strategy.

        Args:
            strategy_id: Unique strategy identifier
            symbols: List of symbols to trade (e.g., ['BTC/USDT'])
            time_frame: Strategy time frame

        Raises:
            ValueError: If strategy_id or symbols is empty
        """
        if not strategy_id:
            raise ValueError("strategy_id cannot be empty")
        if not symbols:
            raise ValueError("symbols list cannot be empty")

        self._strategy_id: str = strategy_id
        self._symbols: List[str] = symbols
        self._time_frame: TimeFrame = time_frame

        # State
        self._state: StrategyState = StrategyState.STOPPED
        self._positions: Dict[str, Position] = {}
        self._signals: List[Signal] = []
        self._ticks_processed: int = 0
        self._errors: int = 0

        # Configuration
        self._config: Dict[str, Any] = {}

        logger.info(f"Strategy {strategy_id} initialized for {len(symbols)} symbols")

    @property
    def id(self) -> str:
        """Get strategy ID."""
        return self._strategy_id

    @property
    def symbols(self) -> List[str]:
        """Get symbols list."""
        return self._symbols.copy()

    @property
    def state(self) -> StrategyState:
        """Get strategy state."""
        return self._state

    @property
    def positions(self) -> Dict[str, Position]:
        """Get current positions."""
        return self._positions.copy()

    @property
    def ticks_processed(self) -> int:
        """Get number of ticks processed."""
        return self._ticks_processed

    @abstractmethod
    def on_tick(self, tick: EnrichedTick) -> Optional[Signal]:
        """
        Process enriched tick and generate signal.

        This is the main strategy logic method.
        Called for each incoming tick from Redis pub/sub.

        Args:
            tick: Enriched tick data with indicators

        Returns:
            Signal if generated, None otherwise

        Example:
            >>> def on_tick(self, tick: EnrichedTick) -> Optional[Signal]:
            ...     rsi = tick.get_indicator('rsiindicator_period14_rsi')
            ...     if rsi < 30:
            ...         return Signal(self.id, tick.symbol, SignalType.BUY, tick.price)
            ...     return None
        """
        pass

    async def initialize(self) -> bool:
        """
        Initialize strategy.

        Called before start(). Load configuration,
        validate parameters, setup resources.

        Returns:
            True if initialization successful

        Example:
            >>> await strategy.initialize()
            True
        """
        logger.info(f"Initializing strategy {self._strategy_id}")
        self._state = StrategyState.RUNNING
        return True

    async def start(self) -> None:
        """
        Start strategy.

        Begins processing ticks. Called after initialize().
        """
        logger.info(f"Starting strategy {self._strategy_id}")
        self._state = StrategyState.RUNNING

    async def stop(self) -> None:
        """
        Stop strategy.

        Stops processing ticks. Cleanup resources.
        """
        logger.info(f"Stopping strategy {self._strategy_id}")
        self._state = StrategyState.STOPPED

    async def pause(self) -> None:
        """Pause strategy."""
        logger.info(f"Pausing strategy {self._strategy_id}")
        self._state = StrategyState.PAUSED

    async def resume(self) -> None:
        """Resume paused strategy."""
        logger.info(f"Resuming strategy {self._strategy_id}")
        self._state = StrategyState.RUNNING

    def process_tick(self, tick: EnrichedTick) -> Optional[Signal]:
        """
        Process tick with state management.

        Wrapper around on_tick() that handles state and error tracking.

        Args:
            tick: Enriched tick data

        Returns:
            Signal if generated, None otherwise
        """
        if self._state != StrategyState.RUNNING:
            return None

        if tick.symbol not in self._symbols:
            return None

        try:
            self._ticks_processed += 1
            signal = self.on_tick(tick)

            if signal:
                self._signals.append(signal)
                logger.info(
                    f"Signal generated: {signal.signal_type.value} "
                    f"{signal.symbol} @ {signal.price}"
                )

            return signal

        except Exception as e:
            logger.error(f"Error processing tick in {self._strategy_id}: {e}")
            self._errors += 1
            return None

    def update_position(self, symbol: str, price: Decimal) -> None:
        """
        Update position with current price.

        Args:
            symbol: Trading pair symbol
            price: Current price
        """
        if symbol in self._positions:
            self._positions[symbol].update_price(price)

    def open_position(
        self,
        symbol: str,
        side: str,
        quantity: Decimal,
        price: Decimal,
    ) -> Position:
        """
        Open new position.

        Args:
            symbol: Trading pair
            side: LONG or SHORT
            quantity: Position size
            price: Entry price

        Returns:
            New position
        """
        position = Position(
            symbol=symbol,
            side=side,
            quantity=quantity,
            entry_price=price,
            current_price=price,
        )
        self._positions[symbol] = position
        logger.info(f"Opened {side} position: {quantity} {symbol} @ {price}")
        return position

    def close_position(self, symbol: str, price: Decimal) -> Optional[Position]:
        """
        Close existing position.

        Args:
            symbol: Trading pair
            price: Close price

        Returns:
            Closed position if existed, None otherwise
        """
        if symbol not in self._positions:
            return None

        position = self._positions.pop(symbol)
        position.update_price(price)

        logger.info(
            f"Closed position: {position.side} {symbol} "
            f"PnL: {position.unrealized_pnl} ({position.pnl_percent:.2f}%)"
        )

        return position

    def get_config(self, key: str, default: Any = None) -> Any:
        """Get configuration value."""
        return self._config.get(key, default)

    def set_config(self, key: str, value: Any) -> None:
        """Set configuration value."""
        self._config[key] = value

    def get_stats(self) -> Dict[str, Any]:
        """
        Get strategy statistics.

        Returns:
            Dictionary with strategy statistics
        """
        active_positions = len([p for p in self._positions.values() if p.unrealized_pnl != 0])
        total_pnl = sum(p.unrealized_pnl for p in self._positions.values())

        return {
            'strategy_id': self._strategy_id,
            'state': self._state.value,
            'symbols': self._symbols,
            'ticks_processed': self._ticks_processed,
            'signals_generated': len(self._signals),
            'active_positions': active_positions,
            'total_unrealized_pnl': float(total_pnl),
            'errors': self._errors,
        }


class StrategyManager:
    """
    Manages multiple strategies.

    Purpose:
        - Start/stop multiple strategies
        - Route enriched ticks to strategies
        - Aggregate signals
        - Monitor strategy health

    Example:
        >>> manager = StrategyManager()
        >>> manager.add_strategy(rsi_strategy)
        >>> manager.add_strategy(macd_strategy)
        >>> await manager.start_all()
        >>> # Process ticks
        >>> for tick in ticks:
        ...     signals = manager.process_tick(tick)
    """

    def __init__(self) -> None:
        """Initialize strategy manager."""
        self._strategies: Dict[str, Strategy] = {}
        self._running: bool = False
        logger.info("StrategyManager initialized")

    def add_strategy(self, strategy: Strategy) -> None:
        """
        Add strategy to manager.

        Args:
            strategy: Strategy instance to add

        Raises:
            ValueError: If strategy ID already exists
        """
        if strategy.id in self._strategies:
            raise ValueError(f"Strategy {strategy.id} already exists")

        self._strategies[strategy.id] = strategy
        logger.info(f"Added strategy: {strategy.id}")

    def remove_strategy(self, strategy_id: str) -> Optional[Strategy]:
        """
        Remove strategy from manager.

        Args:
            strategy_id: Strategy ID to remove

        Returns:
            Removed strategy if existed, None otherwise
        """
        strategy = self._strategies.pop(strategy_id, None)
        if strategy:
            logger.info(f"Removed strategy: {strategy_id}")
        return strategy

    def get_strategy(self, strategy_id: str) -> Optional[Strategy]:
        """Get strategy by ID."""
        return self._strategies.get(strategy_id)

    def list_strategies(self) -> List[str]:
        """Get list of strategy IDs."""
        return list(self._strategies.keys())

    async def start_all(self) -> None:
        """Start all strategies."""
        logger.info(f"Starting {len(self._strategies)} strategies")
        self._running = True

        for strategy in self._strategies.values():
            try:
                await strategy.initialize()
                await strategy.start()
            except Exception as e:
                logger.error(f"Failed to start strategy {strategy.id}: {e}")

    async def stop_all(self) -> None:
        """Stop all strategies."""
        logger.info("Stopping all strategies")
        self._running = False

        for strategy in self._strategies.values():
            try:
                await strategy.stop()
            except Exception as e:
                logger.error(f"Error stopping strategy {strategy.id}: {e}")

    def process_tick(self, tick: EnrichedTick) -> List[Signal]:
        """
        Process tick through all strategies.

        Args:
            tick: Enriched tick data

        Returns:
            List of signals generated by all strategies
        """
        if not self._running:
            return []

        signals = []

        for strategy in self._strategies.values():
            try:
                signal = strategy.process_tick(tick)
                if signal:
                    signals.append(signal)
            except Exception as e:
                logger.error(f"Error in strategy {strategy.id}: {e}")

        return signals

    def get_all_signals(self) -> List[Signal]:
        """Get all signals from all strategies."""
        signals = []
        for strategy in self._strategies.values():
            signals.extend(strategy._signals)
        return signals

    def get_stats(self) -> Dict[str, Any]:
        """Get statistics for all strategies."""
        return {
            'running': self._running,
            'strategy_count': len(self._strategies),
            'strategies': {
                sid: strat.get_stats()
                for sid, strat in self._strategies.items()
            },
        }
